version: "3.8"

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_DB=nomhunter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - local
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    entrypoint: redis-server --requirepass password123
    ports:
      - 6379:6379
    volumes:
      - redis:/data/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  postgres:
  redis:
