version: "3.8"

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_DB=nomhunter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nomhunter.com
      - PGADMIN_DEFAULT_PASSWORD=nomnom
      - PGADMIN_LISTEN_PORT=5454
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5454:5454/tcp
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
